#!/usr/bin/env node
/**
 * SABOTAGE VERIFICATION.
 *
 * A test that has never failed is a rumour. This harness breaks the code on
 * purpose, one edit at a time, and asserts that a NAMED test notices. If the
 * suite still passes, the test was decorative and gets rewritten.
 *
 * Across the previous project this exposed 16 worthless tests. It is not
 * optional here either.
 *
 * Usage: node tools/sabotage.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const CASES = [
  {
    name: 'guard verifies only once, then trusts the environment',
    file: 'src/core/guard.js',
    from: '    if (halted) throw new EnvironmentError(halted);\n\n    const snap = await snapshot();',
    to: '    if (halted) throw new EnvironmentError(halted);\n    if (globalThis.__seen) return;\n    globalThis.__seen = true;\n    const snap = await snapshot();',
    expect: 'verifies before EVERY action',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'guard un-latches as soon as the tab looks fine again',
    file: 'src/core/guard.js',
    from: '    if (halted) throw new EnvironmentError(halted);',
    to: '    if (halted) { const s = await snapshot(); if (verify(binding, s, { surfaces: [surface] }).ok) halted = null; }\n    if (halted) throw new EnvironmentError(halted);',
    expect: 'LATCHES',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'a forbidden action is checked AFTER the transport is called',
    file: 'src/core/guard.js',
    from: "    assertAllowed(action); // throws ForbiddenActionError; default-deny\n    await ensure(surface);",
    to: '    await ensure(surface);',
    expect: 'WITHOUT touching the transport',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'action policy becomes default-ALLOW (only the blacklist is checked)',
    file: 'src/core/actions.js',
    from: "  throw new ForbiddenActionError(action, 'unknown action, and the policy is default-deny');",
    to: '  return action;',
    expect: 'DEFAULT-DENY',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'readiness is reported before a conversation switch',
    file: 'src/core/environment.js',
    from: '    if (s.conversationId !== b.conversationId) {',
    to: '    if (s.ready === false) {\n      problems.push(problem(key, b.label, \'not-ready\', \'the page is not currently interactive\'));\n      continue;\n    }\n    if (s.conversationId !== b.conversationId) {',
    expect: 'even while the page is still loading',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'binding accepts a tab with no conversation id (a fresh "new chat")',
    file: 'src/core/environment.js',
    from: '    if (!s.conversationId) {',
    to: '    if (false && !s.conversationId) {',
    expect: 'would CREATE a chat',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'two roles are allowed to share one tab',
    file: 'src/core/environment.js',
    from: '      problems.push(\n        problem(key, b.label, \'ambiguous\', `shares tab ${b.tabId} with "${byTab.get(b.tabId)}"`),\n      );',
    to: '      byTab.set(b.tabId, key);',
    expect: 'ambiguous, not clever',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'a missing REQUIRED tab is tolerated',
    file: 'src/core/environment.js',
    from: "        problems.push(problem(spec.key, spec.label, 'tab-missing', 'no pre-opened tab was reported'));",
    to: '        void 0;',
    expect: 'refuses to bind',
    test: 'test/environment.test.mjs',
  },
  {
    name: 'environment drift is recorded as a terminal failure',
    file: 'src/core/orchestrator.js',
    from: "    this.memory.status = 'blocked';\n    this.memory.phase = this.memory.phase || 'plan';",
    to: "    this.memory.status = 'failed';\n    this.memory.phase = this.memory.phase || 'plan';",
    expect: 'NOT a failure',
    test: 'test/blocking.test.mjs',
  },
  {
    name: 'the block reason lives in a variable instead of the store',
    file: 'src/core/orchestrator.js',
    from: '    this.memory.block = { at: Date.now(), where, problems, detail };\n    await this.save();',
    to: '    this._block = { at: Date.now(), where, problems, detail };\n    await this.save();',
    expect: 'PERSISTED',
    test: 'test/blocking.test.mjs',
  },
  {
    name: 'a blocked run silently re-probes and resumes itself',
    file: 'src/core/orchestrator.js',
    from: '    if (this.memory.block) {\n      const held = {',
    to: '    if (false && this.memory.block) {\n      const held = {',
    expect: 'refuses to restart until a human',
    test: 'test/blocking.test.mjs',
  },
  {
    name: 'the environment is checked once per run instead of per phase',
    file: 'src/core/orchestrator.js',
    from: '      await this.gate(\'execute\', record, () => this.phaseExecute(record));',
    to: '      await this.phaseExecute(record);',
    expect: 'halts at the next phase boundary',
    test: 'test/blocking.test.mjs',
  },
  {
    name: 'a throwing environment probe counts as a pass',
    file: 'src/core/orchestrator.js',
    from: '    } catch (err) {\n      /*\n       * A CHECK THAT THROWS IS A FAILED CHECK, NOT A PASSED ONE.',
    to: '    } catch (err) {\n      return true;\n      /*\n       * A CHECK THAT THROWS IS A FAILED CHECK, NOT A PASSED ONE.',
    expect: 'THROWS is a failed check',
    test: 'test/blocking.test.mjs',
  },
  {
    name: 'the journal keeps the newest events and drops the start of the run',
    file: 'src/core/journal.js',
    from: '      const keepHead = Math.floor(this.limit * 0.25);',
    to: '      const keepHead = 0;',
    expect: 'drops the MIDDLE',
    test: 'test/journal.test.mjs',
  },
  {
    name: 'the journal renders scraped text without redacting it',
    file: 'src/core/journal.js',
    from: '  for (const [re, with_] of SECRETS) out = out.replace(re, with_);',
    to: '  /* redaction removed */',
    expect: 'RENDERED log',
    test: 'test/journal.test.mjs',
  },
  /* ---- logging & observability (session 3) ------------------------- */
  {
    name: 'the durable sink quietly writes only part of each batch',
    file: 'src/core/logger.js',
    from: '      await this.sink.append(batch);',
    to: '      await this.sink.append(batch.slice(0, 1));',
    expect: 'durable sink receives every event',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'a failed sink write drops the batch instead of retrying',
    file: 'src/core/logger.js',
    from: '      this.pending = [...batch, ...this.pending];',
    to: '      /* dropped */',
    expect: 'retains events for retry',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'the live view drops events without counting them',
    file: 'src/core/logger.js',
    from: '      this.notShown += removed;',
    to: '      /* silently */',
    expect: 'reports what it is not showing',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'a throwing UI subscriber kills the log entry',
    file: 'src/core/logger.js',
    from: '    try {\n      this.onEvent(event);\n    } catch (err) {',
    to: '    if (true) {\n      this.onEvent(event);\n    } else if (false) { const err = null;',
    expect: 'throwing UI subscriber cannot lose an event',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'begin() logs only on completion, so waits are invisible',
    file: 'src/core/logger.js',
    from: "    const open = this.log(type, { ...fields, status: 'pending', at: startedAt });",
    to: "    const open = makeEvent(type, { ...fields, status: 'pending', at: startedAt });\n    open.id = this.nextId();",
    expect: 'logs the wait immediately',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'event ids become timestamps, losing the total order',
    file: 'src/core/events.js',
    from: '  return () => `evt-${sessionId}-${String(++seq).padStart(6, \'0\')}`;',
    to: '  return () => `evt-${sessionId}-${Date.now()}`;',
    expect: 'unique AND sortable',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'unknown event types are accepted silently',
    file: 'src/core/events.js',
    from: '  if (!spec) throw new TypeError(`unknown event type: ${type}`);',
    to: '  if (!spec) return { type, at: Date.now() };',
    expect: 'unknown event type is rejected',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'the summary counts prompts from a counter that can drift',
    file: 'src/core/logger.js',
    from: "    promptsSent: count('prompt-submitted'),",
    to: '    promptsSent: 0,',
    expect: 'DERIVED from events',
    test: 'test/logging.test.mjs',
  },
  {
    name: 'an unmapped engine event is silently dropped',
    file: 'src/core/bridge.js',
    from: "    if (type === undefined) {\n      logger.log('error', {",
    to: "    if (type === undefined) return;\n    if (false) {\n      logger.log('error', {",
    expect: 'logged as a gap, never dropped',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'a skipped evidence phase no longer blocks completion',
    file: 'src/core/controls.js',
    from: '  return !EVIDENCE_PHASES.some((p) => skipped.includes(p));',
    to: '  return true;',
    expect: 'may NOT skip your way to',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'skip is recorded but stop.js ignores it',
    file: 'src/core/stop.js',
    from: '      if (!iterationIsTrustworthy(deciding)) {',
    to: '      if (false && !iterationIsTrustworthy(deciding)) {',
    expect: 'may NOT skip your way to',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'an OLD skip poisons every later iteration',
    file: 'src/core/stop.js',
    from: '      const deciding = memory.history?.[memory.history.length - 1];',
    to: '      const deciding = memory.history?.find((r) => (r.skipped || []).length) || memory.history?.[memory.history.length - 1];',
    expect: 'does not block a later honest one',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'the panel reports a phase while an AI response is pending',
    file: 'src/core/status.js',
    from: "  if (lastEvent?.status === 'pending') {\n    return {\n      text: lastEvent.label,",
    to: "  if (false) {\n    return {\n      text: lastEvent.label,",
    expect: 'outranks the phase',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'error resolution goes back to comparing timestamps',
    file: 'src/core/status.js',
    from: '        (x) => x.id > e.id && x.status === ',
    to: '        (x) => x.at > e.at && x.status === ',
    expect: 'resolved by a later success',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'currentAI names ChatGPT during local loop detection',
    file: 'src/core/status.js',
    from: '  if (LOCAL_PHASES.has(memory?.phase)) return null;',
    to: '  /* removed */',
    expect: 'null when nobody has the floor',
    test: 'test/observability.test.mjs',
  },
  {
    name: 'unavailable controls are hidden instead of disabled',
    file: 'src/core/controls.js',
    from: '    out[c.key] = {\n      label: c.label,\n      enabled: ok,',
    to: '    if (!ok) continue;\n    out[c.key] = {\n      label: c.label,\n      enabled: ok,',
    expect: 'disabled rather than omitted',
    test: 'test/ui.test.mjs',
  },
  {
    name: 'log entries are rendered without escaping',
    file: 'extension/ui.js',
    from: "    .replace(/</g, '&lt;')",
    to: '    .replace(/\\u0000/g, \'\')',
    expect: 'every interpolated value is escaped',
    test: 'test/ui.test.mjs',
  },
  {
    name: 'the health percentage is shown without its evidence fraction',
    file: 'extension/ui.js',
    from: '       <span class="muted small">${s.measuredDimensions}/${s.totalDimensions} dimensions measured</span>',
    to: '       ',
    expect: 'without its evidence fraction',
    test: 'test/ui.test.mjs',
  },
  {
    name: 'the truncation banner is removed from the log view',
    file: 'extension/ui.js',
    from: '  const banner = notShown > 0',
    to: '  const banner = false',
    expect: 'how many events the view is not showing',
    test: 'test/ui.test.mjs',
  },
  /* ---- first-run workflow (session 4) ------------------------------ */
  {
    name: 'the parser honours a nextObjective from the engineer',
    file: 'src/core/report.js',
    from: '  for (const key of FORBIDDEN_FIELDS) {\n    if (key in obj) {',
    to: '  for (const key of []) {\n    if (key in obj) {',
    expect: 'CANNOT SET DIRECTION',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'a test suite that never ran counts as a clean run',
    file: 'src/core/report.js',
    from: "  if (t && t.ran !== false && (num(t.passed) + num(t.failed) + num(t.skipped)) > 0) {",
    to: '  if (t) {',
    expect: 'produces NO evidence, not a zero',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'a missing report block is treated as an empty success',
    file: 'src/core/report.js',
    from: "  if (!raw) {\n    return {\n      ok: false,",
    to: "  if (!raw) {\n    return {\n      ok: true,",
    expect: 'loud failure, not an empty success',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'any JSON code block is accepted as the report',
    file: 'src/core/report.js',
    from: '      if (required.some((k) => k in obj)) fb = body;',
    to: '      fb = body;',
    expect: 'NOT mistaken for the report',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: '"complete" with failing tests is no longer contradicted',
    file: 'src/core/report.js',
    from: "  if (report.taskStatus === 'complete' && t.ran !== false && num(t.failed) > 0) {",
    to: '  if (false) {',
    expect: 'contradicted by its own numbers',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'the file list no longer yields a diff record',
    file: 'src/core/report.js',
    from: "  } else if (Array.isArray(report.filesModified) && report.filesModified.length) {",
    to: '  } else if (false) {',
    expect: 'diff record is derived from the file list',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'explore mode gets an empty objective heading to fill in',
    file: 'src/core/protocol.js',
    from: "    parts.push(explorationBrief());",
    to: "    parts.push(explorationBrief());\n    parts.push('## OBJECTIVE\\n\\n');",
    expect: 'NO objective section',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'scores are sent to the engineer without their confidence',
    file: 'src/core/protocol.js',
    from: '      lines.push(`  - ${s.dimension}: ${s.score}% (${s.confidence})`);',
    to: '      lines.push(`  - ${s.dimension}: ${s.score}%`);',
    expect: 'WITH their confidence',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'the metadata block grows without bound',
    file: 'src/core/protocol.js',
    from: '    for (const i of memory.openIssues.slice(0, maxIssues)) lines.push(`  - ${clip(i, 160)}`);',
    to: '    for (const i of memory.openIssues) lines.push(`  - ${i}`);',
    expect: 'bounded so it cannot push the protocol',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'the manager plans the baseline iteration after all',
    file: 'src/core/orchestrator.js',
    from: '    const objective = this.memory.baselineDone\n      ? await this.manager.plan({',
    to: '    const objective = true\n      ? await this.manager.plan({',
    expect: 'does NOT consult the manager',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'an empty baseline is marked done anyway',
    file: 'src/core/orchestrator.js',
    from: '    if (!this.memory.baselineDone && record.baseline && record.summary) {',
    to: '    if (!this.memory.baselineDone && record.baseline) {',
    expect: 'produced nothing RUNS AGAIN',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'a stored project with history defaults to mode "new"',
    file: 'src/core/orchestrator.js',
    from: "    if (!this.memory.mode) this.memory.mode = this.memory.history?.length ? 'existing' : mode;",
    to: '    if (!this.memory.mode) this.memory.mode = mode;',
    expect: 'not mistaken for new',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'New Project accepts a two-word description',
    file: 'src/core/modes.js',
    from: '    } else if (text.length < 20) {',
    to: '    } else if (false) {',
    expect: 'refuses an empty or throwaway description',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'preflight trusts a flush that returned no error',
    file: 'src/core/preflight.js',
    from: '      const failed = flushed?.error || logger.sinkFailures.length > failuresBefore;',
    to: '      const failed = Boolean(flushed?.error);',
    expect: 'broken durable log is a WARNING',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'preflight leaves its probe in the stored project',
    file: 'src/core/preflight.js',
    from: '      await store.save(existing || null);',
    to: '      /* probe left in place */',
    expect: 'leaves an existing stored project intact',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'the workspace check cannot tell "no tab" from "wrong page"',
    file: 'src/core/preflight.js',
    from: "          ? `the Arena tab is on ${rawEngineer.url || 'an unknown URL'}, which does not look like a project workspace`",
    to: "          ? 'no Arena tab was reported, so no workspace could be checked'",
    expect: 'outside a workspace fails the workspace check',
    test: 'test/firstrun.test.mjs',
  },
  /* ---- packaging (session 5) --------------------------------------- */
  {
    name: 'an IndexedDB rejection carries no Error object',
    file: 'extension/idbsink.js',
    from: "      req.onerror = () => reject(req.error || new Error('IndexedDB could not be opened'));",
    to: '      req.onerror = () => reject(req.error);',
    expect: 'DEGRADES HONESTLY when storage is unavailable',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'the worker reports an error about the error',
    file: 'extension/background.js',
    from: "const reason = (err) => String(err?.message || err || 'unknown error');",
    to: 'const reason = (err) => String(err.message);',
    expect: 'names the real problem even when a rejection carries nothing',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'broadcast() is not guarded against a synchronous throw',
    file: 'extension/background.js',
    from: '    const p = chrome.runtime.sendMessage({ kind: \'state\', state: snapshot() });\n    if (p?.catch) p.catch(() => {});',
    to: "    chrome.runtime.sendMessage({ kind: 'state', state: snapshot() });",
    expect: 'survives a browser with no panel open',
    test: 'test/packaging.test.mjs',
  },
  /* ---- the silent button (session 6) ------------------------------- */
  {
    name: 'client.js loses its preflight method again',
    file: 'extension/client.js',
    from: "    preflight: (setup) => send('preflight', { setup }),",
    to: '',
    expect: 'implements every method the panel calls',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'the panel goes back to optional-calling controls',
    file: 'extension/panel.js',
    from: "        if (typeof engine.preflight !== 'function') {\n          throw new Error('the \"preflight\" control is not connected to the background worker');\n        }\n",
    to: '',
    expect: 'missing control produces a visible error',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'click handlers are unwrapped, so a throw vanishes',
    file: 'extension/panel.js',
    from: "  root.addEventListener('click', (ev) => guarded(describeTarget(ev.target), async () => {",
    to: "  root.addEventListener('click', async (ev) => { const _ = 0;",
    expect: 'every UI handler is wrapped',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'a storage warning blocks the run again',
    file: 'src/core/preflight.js',
    from: '    ok: blocking.length === 0,',
    to: '    ok: failed.length === 0,',
    expect: 'warning does not block the run',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'checks default to non-blocking',
    file: 'src/core/preflight.js',
    from: "function check(key, label, ok, detail = '', remedy = '', blocking = true) {",
    to: "function check(key, label, ok, detail = '', remedy = '', blocking = false) {",
    expect: 'blocking by default',
    test: 'test/firstrun.test.mjs',
  },
  {
    name: 'the probe accepts a new-chat tab as a conversation',
    file: 'extension/probe.js',
    from: '      conversationId: conversationIdFor(spec, tab.url),',
    to: "      conversationId: conversationIdFor(spec, tab.url) || 'new',",
    expect: 'new-chat screen yields no conversation id',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'duplicate tabs for one role are silently collapsed',
    file: 'extension/probe.js',
    from: '      (ambiguous[spec.key] ||= [surfaces[spec.key]]).push(entry);',
    to: '      /* ignored */',
    expect: 'record the ambiguity',
    test: 'test/packaging.test.mjs',
  },
  /* ---- surface scanner (session 7) --------------------------------- */
  {
    name: 'a failed scan is allowed to trigger another scan',
    file: 'src/core/surface.js',
    from: '    if (NEVER_SCAN.has(event.type)) return decline(`"${event.type}" must never trigger a scan`);',
    to: '    /* loop */',
    expect: 'CANNOT TRIGGER ANOTHER SCAN',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the reentrancy latch is removed',
    file: 'src/core/surface.js',
    from: "    if (this.busy) return decline('a scan is already running');",
    to: '    /* reentrant */',
    expect: 'reentrancy latch',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the per-surface cooldown is ignored',
    file: 'src/core/surface.js',
    from: '    if (last && now - last < this.config.cooldownMs) {',
    to: '    if (false) {',
    expect: 'not rescanned within the cooldown',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the session budget is unlimited',
    file: 'src/core/surface.js',
    from: '    if (this.used >= this.config.maxPerSession) {',
    to: '    if (false) {',
    expect: 'session budget is finite',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'every error triggers a scan, not just page-level ones',
    file: 'src/core/surface.js',
    from: '    if (!SCAN_WORTHY.has(event.type)) return decline(`"${event.type}" is not a page-level failure`);',
    to: '    /* all errors */',
    expect: 'only page-level failures are scanned',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'captures are stored unredacted',
    file: 'src/core/surface.js',
    from: '    const t = redact(String(s ?? \'\')).replace(/\\s+/g, \' \').trim();',
    to: "    const t = String(s ?? '').replace(/\\s+/g, ' ').trim();",
    expect: 'CAPTURE IS REDACTED',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'trimming for size drops the signals instead of the nodes',
    file: 'src/core/surface.js',
    from: '    const keep = Math.max(20, Math.floor(nodes.length / 2));\n    capture.nodes = nodes.slice(0, keep);',
    to: '    const keep = nodes.length;\n    capture.signals = [];\n    capture.nodes = nodes.slice(0, keep);',
    expect: 'SIGNALS survive',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the node cap is removed, so a capture can be unbounded',
    file: 'src/core/surface.js',
    from: '  const nodes = (raw.nodes || []).slice(0, cfg.maxNodes).map((n) => ({',
    to: '  const nodes = (raw.nodes || []).map((n) => ({',
    expect: 'bounded in nodes and in bytes',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'an unchanged page is not reported as stuck',
    file: 'src/core/surface.js',
    from: '    unchanged: appeared.length === 0 && vanished.length === 0 && changed.length === 0 && newSignals.length === 0,',
    to: '    unchanged: false,',
    expect: 'reported as STUCK',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the journal stops carrying page captures',
    file: 'src/core/journal.js',
    from: "    const scans = this.events.filter((e) => e.type === 'surface-scan' && e.data?.markdown);",
    to: '    const scans = [];',
    expect: 'captures appear in the exported markdown',
    test: 'test/surface.test.mjs',
  },
  {
    name: 'the automatic trigger is disconnected from the logger',
    file: 'extension/background.js',
    from: '    void maybeScan(event);',
    to: '    /* disconnected */',
    expect: 'automatically captures the page behind it',
    test: 'test/packaging.test.mjs',
  },
  /* ---- production build (session 8) -------------------------------- */
  {
    name: 'asserted scores can carry a run over the target again',
    file: 'src/core/stop.js',
    from: '      if (evidenced.length < cfg.minEvidencedDimensions) {',
    to: '      if (false) {',
    expect: 'FLATTERY CANNOT REACH THE TARGET',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'opinions may lift a weak evidenced score over the line',
    file: 'src/core/stop.js',
    from: '      if (evidencedScore < cfg.target) {',
    to: '      if (false) {',
    expect: 'OPINION CANNOT CARRY THE RUN',
    test: 'test/stop-guard.test.mjs',
  },
  {
    name: 'the manager may write code after all',
    file: 'src/core/schema.js',
    from: '      if (lower.has(key.toLowerCase())) {',
    to: '      if (false) {',
    expect: 'MANAGER CANNOT WRITE CODE',
    test: 'test/schema.test.mjs',
  },
  {
    name: 'a measured claim with no basis is believed',
    file: 'src/core/schema.js',
    from: "    if (confidence === 'measured' && basis.length === 0) {",
    to: '    if (false) {',
    expect: 'DOWNGRADED, not accepted or rejected',
    test: 'test/schema.test.mjs',
  },
  {
    name: 'a basis naming absent evidence is accepted',
    file: 'src/core/schema.js',
    from: '    const hit = EVIDENCE_KINDS.find((k) => b.toLowerCase().includes(k));\n    if (hit && kinds.has(hit)) out.push({ kind: hit, note: b });',
    to: '    const hit = EVIDENCE_KINDS.find((k) => b.toLowerCase().includes(k));\n    if (hit) out.push({ kind: hit, note: b });',
    expect: 'never produced does not count',
    test: 'test/schema.test.mjs',
  },
  {
    name: 'hedged prose becomes measured test evidence',
    file: 'src/core/parse.js',
    from: '    if (HEDGES.test(line)) continue;',
    to: '    if (false) continue;',
    expect: 'PROSE NEVER BECOMES MEASURED',
    test: 'test/parse.test.mjs',
  },
  {
    name: 'the jest composite pattern is tried after the simple one',
    file: 'src/core/parse.js',
    from: "  {\n    name: 'jest-summary',",
    to: "  {\n    name: 'generic-first',\n    re: /(\\d[\\d,_]*)\\s*passed/i,\n    take: (m) => ({ passed: int(m[1]), failed: 0, skipped: 0 }),\n  },\n  {\n    name: 'jest-summary',",
    expect: 'NOT READ AS CLEAN',
    test: 'test/parse.test.mjs',
  },
  {
    name: 'build success wins over build failure',
    file: 'src/core/parse.js',
    from: '  for (const p of BUILD_FAIL) {\n    const m = p.re.exec(src);\n    if (m && !HEDGES.test(lineAround(src, m.index))) {\n      return makeEvidence(\'build\', {\n        ok: false,',
    to: '  for (const p of BUILD_FAIL) {\n    const m = null;\n    if (m) {\n      return makeEvidence(\'build\', {\n        ok: false,',
    expect: 'build failure beats build success',
    test: 'test/parse.test.mjs',
  },
  {
    name: 'phases are no longer idempotent',
    file: 'src/core/session.js',
    from: '  return (run.completedPhases || []).includes(phase);',
    to: '  return false;',
    expect: 'not executed twice on resume',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'a newer schema version is silently downgraded',
    file: 'src/core/migrate.js',
    from: '  if (from > target) {',
    to: '  if (false) {',
    expect: 'NEWER BUILD IS REFUSED',
    test: 'test/session.test.mjs',
  },
  {
    name: 'a corrupt project is deleted instead of quarantined',
    file: 'src/core/projectstore.js',
    from: '      await this.kv.set(`quarantine:${index.activeProjectId}:${Date.now()}`, m.original ?? rawProject);',
    to: '      await this.kv.remove(K.project(index.activeProjectId));',
    expect: 'QUARANTINED, not deleted',
    test: 'test/session.test.mjs',
  },
  {
    name: 'a migrated running run stays running',
    file: 'src/core/migrate.js',
    from: "      state: data.status === 'running' ? 'paused' : (data.status ?? 'idle'),",
    to: "      state: data.status ?? 'idle',",
    expect: 'is PAUSED, never running',
    test: 'test/session.test.mjs',
  },
  {
    name: 'user stop is erased by start() again',
    file: 'src/core/runner.js',
    from: "    if (run.state === 'stopped' && run.stopReason === 'user-stopped') {",
    to: '    if (false) {',
    expect: 'user stop is honoured',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'repeated failures loop forever instead of stopping',
    file: 'src/core/runner.js',
    from: '      if (this.consecutiveFailures >= MAX_CONSECUTIVE_FAILURES) {',
    to: '      if (false) {',
    expect: 'STOPS the run rather than looping',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'a dead tab is retried like a timeout',
    file: 'src/adapters/base.js',
    from: "        if (outcome !== 'timed-out' || attempt >= this.policy.timeoutRetries) {",
    to: '        if (attempt >= this.policy.timeoutRetries) {',
    expect: 'closed tab does NOT retry',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'an empty AI reply counts as a valid response',
    file: 'src/adapters/base.js',
    from: "          throw new AdapterError('failed', `${this.role} returned an empty response`, { what });",
    to: '          return "";',
    expect: 'empty response is a failure',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'a malformed engineer reply discards its real numbers',
    file: 'src/adapters/engineer.js',
    from: '      const salvaged = parseAll(text, iterationCtx);',
    to: '      const salvaged = { evidence: [] };',
    expect: 'STILL YIELDS ITS REAL NUMBERS',
    test: 'test/integration.test.mjs',
  },
  {
    name: 'the transport accepts the previous answer as the new one',
    file: 'src/transports/dom.js',
    from: '      return s.turns > baseTurns || (s.lastText && s.lastText !== baseText);',
    to: '      return true;',
    expect: 'NOT RETURN THE PREVIOUS ANSWER',
    test: 'test/transport.test.mjs',
  },
  {
    name: 'an unknown busy state is treated as idle',
    file: 'src/transports/dom.js',
    from: '        const need = s.busyKnown ? this.config.quietMs : this.config.blindQuietMs;',
    to: '        const need = this.config.quietMs;',
    expect: 'UNKNOWN busy state waits longer',
    test: 'test/transport.test.mjs',
  },
  {
    name: 'the transport types into a page that is already generating',
    file: 'src/transports/dom.js',
    from: '      if (!idle) throw new TransportError',
    to: '      if (false) throw new TransportError',
    expect: 'REFUSES TO TYPE INTO A PAGE',
    test: 'test/transport.test.mjs',
  },
  {
    name: 'analytics invent a value where there is no data',
    file: 'src/core/analytics.js',
    from: "const UNKNOWN = (note) => ({ value: null, basis: 'unknown', n: 0, note });",
    to: "const UNKNOWN = (note) => ({ value: 0, basis: 'measured', n: 0, note });",
    expect: 'UNKNOWN, never zero',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'regressions are counted across untested iterations',
    file: 'src/core/analytics.js',
    from: '    .filter((x) => x.e);',
    to: '    .map((x) => (x.e ? x : { n: x.n, e: { passed: 0, failed: 0, total: 0 } }));',
    expect: 'BOTH ran tests',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'a download is complete because the browser accepted it',
    file: 'src/core/artifacts.js',
    from: "      const status = await this.downloader.probe(id);\n      if (status?.state === 'complete') {",
    to: "      const status = { state: 'complete', bytes: 1 };\n      if (status?.state === 'complete') {",
    expect: 'never lands is interrupted',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'a zero-byte download counts as complete',
    file: 'src/core/artifacts.js',
    from: '        if (artifact.bytes === 0) {',
    to: '        if (false) {',
    expect: 'zero-byte',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'artifacts are deduplicated globally, losing later reports',
    file: 'src/core/artifacts.js',
    from: '    return `${iteration ?? \'-\'}::${filename}`;',
    to: '    return String(filename);',
    expect: 'per ITERATION, not globally',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'replay ignores iteration-finished for the cursor',
    file: 'src/core/replay.js',
    from: '      s.iteration = Math.max(s.iteration, n);',
    to: '      /* cursor not advanced */',
    expect: 'several sessions of one run order correctly',
    test: 'test/analytics.test.mjs',
  },
  {
    name: 'the UI shows a health score without its evidence fraction',
    file: 'extension/ui.js',
    from: '      ${evidenced} of ${scores.length} dimensions rest on evidence —',
    to: '      ',
    expect: 'colours by CONFIDENCE',
    test: 'test/ui.test.mjs',
  },
  /* ---- arena URL resolution (session 9) ---------------------------- */
  {
    name: 'the generic URL fallback is removed again',
    file: 'extension/probe.js',
    from: '  if (!spec.generic) return null;',
    to: '  return null;\n  // eslint-disable-next-line no-unreachable',
    expect: 'ARENA CONVERSATION URLS RESOLVE',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'the fallback accepts reserved pages as conversations',
    file: 'extension/probe.js',
    from: '      if (NOT_A_CONVERSATION.has(seg.toLowerCase())) continue;',
    to: '      /* no reserved-word guard */',
    expect: 'NON-conversation Arena page still yields no id',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'a failed tab check hides the URL it found',
    file: 'src/core/preflight.js',
    from: "        ? `${p.detail}${seen?.url ? ` — the tab is on ${seen.url}` : ''}`",
    to: '        ? p.detail',
    expect: 'SHOWS THE URL IT FOUND',
    test: 'test/packaging.test.mjs',
  },
  /* ---- verified platform facts (session 10) ------------------------ */
  {
    name: 'the run is awaited inside the message handler again',
    file: 'extension/background.js',
    from: '    return { ok: true, started: true, runId: projectStore.run?.id ?? null };',
    to: '    return activeRun;',
    expect: 'NOT AWAITED INSIDE ONE MESSAGE EVENT',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'the timeout goes back onto Chrome\'s five-minute ceiling',
    file: 'src/adapters/base.js',
    from: '  timeoutMs: 240_000,',
    to: '  timeoutMs: 300_000,',
    expect: 'UNDER Chrome',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'the keep-alive runs unconditionally',
    file: 'extension/background.js',
    from: '    if (!running) { stopHeartbeat(); return; }',
    to: '    /* always alive */',
    expect: 'keep-alive runs only while a run is in flight',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'a read-only shared ChatGPT conversation becomes bindable',
    file: 'extension/probe.js',
    from: '    id: [/\\/g\\/[^/]+\\/c\\/([0-9a-zA-Z-]+)/, /\\/c\\/([0-9a-zA-Z-]+)/],',
    to: '    id: [/\\/g\\/[^/]+\\/c\\/([0-9a-zA-Z-]+)/, /\\/c\\/([0-9a-zA-Z-]+)/, /\\/share\\/([0-9a-zA-Z-]+)/],',
    expect: 'SHARED ChatGPT conversation is NOT bindable',
    test: 'test/packaging.test.mjs',
  },
  {
    name: 'custom-GPT conversation URLs stop resolving',
    file: 'extension/probe.js',
    from: '    id: [/\\/g\\/[^/]+\\/c\\/([0-9a-zA-Z-]+)/, /\\/c\\/([0-9a-zA-Z-]+)/],',
    to: '    id: [/\\/xx\\/([0-9a-zA-Z-]+)/],',
    expect: 'including custom GPTs',
    test: 'test/packaging.test.mjs',
  },
];

let caught = 0;
const missed = [];

for (const [i, c] of CASES.entries()) {
  const original = readFileSync(c.file, 'utf8');
  if (!original.includes(c.from)) {
    missed.push(`${c.name} — PATCH DID NOT APPLY (the anchor text moved)`);
    console.log(`${i + 1}/${CASES.length}  SKIP  ${c.name}`);
    continue;
  }
  writeFileSync(c.file, original.replace(c.from, c.to));

  let output = '';
  try {
    output = execFileSync('node', ['--test', c.test], { encoding: 'utf8', timeout: 60000 });
  } catch (err) {
    output = String(err.stdout || '') + String(err.stderr || '');
  } finally {
    writeFileSync(c.file, original);
  }

  const failures = output
    .split('\n')
    .filter((l) => l.startsWith('not ok '))
    .join('\n');

  const noticed = failures.includes(c.expect);
  if (noticed) {
    caught++;
    console.log(`${i + 1}/${CASES.length}  CAUGHT  ${c.name}`);
  } else {
    missed.push(`${c.name} — expected a failure mentioning "${c.expect}"; got:\n${failures || '(suite still green)'}`);
    console.log(`${i + 1}/${CASES.length}  MISSED  ${c.name}`);
  }
}

console.log(`\n${caught}/${CASES.length} sabotages caught`);
if (missed.length) {
  console.error('\nUNCAUGHT — these tests do not test what they claim:\n' + missed.map((m) => `  - ${m}`).join('\n'));
  process.exit(1);
}
